/**
 * Machine-generated file. Do not modify.
 */

#ifndef _SPECIALCLASSES_H
#define _SPECIALCLASSES_H
#define ENTRY_CLASS 0
#define JAVA_LANG_OBJECT 1
#define JAVA_LANG_THREAD 2
#define JAVA_LANG_BOOT_THREAD 3
#define JAVA_LANG_THROWABLE 4
#define JAVA_LANG_OUTOFMEMORYERROR 5
#define JAVA_LANG_NOSUCHMETHODERROR 6
#endif _SPECIALCLASSES_H
