
## You only need to modify this if you're
## going to rebuild tinyvm.srec.

BINDIR = /usr/bin
BINPREFIX = h8300-hms-
JAVA = java
JAVA_HOME ?= $(JAVA_HOME)

export BINDIR
export BINPREFIX
export JAVA
export CLASSPATH
export JAVA_HOME
