/**
 * Machine-generated file. Do not modify.
 */

#ifndef _SPECIALCLASSES_H
#define _SPECIALCLASSES_H
#define JAVA_LANG_OBJECT 0
#define JAVA_LANG_THREAD 1
#define JAVA_LANG_STRING 2
#define JAVA_LANG_RUNTIME 3
#define JAVA_LANG_THROWABLE 4
#define JAVA_LANG_ERROR 5
#define JAVA_LANG_OUTOFMEMORYERROR 6
#define JAVA_LANG_NOSUCHMETHODERROR 7
#define JAVA_LANG_STACKOVERFLOWERROR 8
#define JAVA_LANG_NULLPOINTEREXCEPTION 9
#define JAVA_LANG_CLASSCASTEXCEPTION 10
#define JAVA_LANG_ARITHMETICEXCEPTION 11
#define JAVA_LANG_ARRAYINDEXOUTOFBOUNDSEXCEPTION 12
#define JAVA_LANG_ILLEGALARGUMENTEXCEPTION 13
#define JAVA_LANG_INTERRUPTEDEXCEPTION 14
#define JAVA_LANG_ILLEGALSTATEEXCEPTION 15
#define JAVA_LANG_ILLEGALMONITORSTATEEXCEPTION 16
#define JAVA_LANG_THREADDEATH 17
#define JOSX_UTIL_TEST 18
#endif // _SPECIALCLASSES_H
