/**
 * Machine-generated file. Do not modify.
 */

#ifndef _SPECIALCLASSES_H
#define _SPECIALCLASSES_H
#define ENTRY_CLASS 0
#define JAVA_LANG_OBJECT 1
#define JAVA_LANG_THREAD 2
#define JAVA_LANG_THROWABLE 3
#define JAVA_LANG_OUTOFMEMORYERROR 4
#define JAVA_LANG_NOSUCHMETHODERROR 5
#define JAVA_LANG_STACKOVERFLOWERROR 6
#define JAVA_LANG_NULLPOINTEREXCEPTION 7
#define JAVA_LANG_CLASSCASTEXCEPTION 8
#define JAVA_LANG_ARITHMETICEXCEPTION 9
#define JAVA_LANG_ARRAYINDEXOUTOFBOUNDSEXCEPTION 10
#endif _SPECIALCLASSES_H
