/**
 * Machine-generated file. Do not modify.
 */

#ifndef _SPECIALCLASSES_H
#define _SPECIALCLASSES_H
#define ENTRY_CLASS 0
#define JAVA_LANG_OBJECT 1
#define JAVA_LANG_THREAD 2
#define JAVA_LANG_STRING 3
#define JAVA_LANG_THROWABLE 4
#define JAVA_LANG_OUTOFMEMORYERROR 5
#define JAVA_LANG_NOSUCHMETHODERROR 6
#define JAVA_LANG_STACKOVERFLOWERROR 7
#define JAVA_LANG_NULLPOINTEREXCEPTION 8
#define JAVA_LANG_CLASSCASTEXCEPTION 9
#define JAVA_LANG_ARITHMETICEXCEPTION 10
#define JAVA_LANG_ARRAYINDEXOUTOFBOUNDSEXCEPTION 11
#endif _SPECIALCLASSES_H
